spring:
  application:
    name: SPRIBE-test-task
  datasource:
    url: jdbc:postgresql://localhost:5432/exchange_db
    username: user
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

app:
  api:
    url: http://apilayer.net/api/live
    access-key: 0ccac8c3d5d02eb4014c5742aad82cd7
  scheduler:
    fixed-rate: 3600000 # 60 minutes
#    fixed-rate: 60000 # 60 seconds

